baseurl = "http://markito.io"
title = "William Markito Oliveira"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]
googleAnalytics = "UA-132475739-1"

[params]
  description = 'Product Manager @ Red Hat'
  logo = "fa-desktop"
  toc = true
  # logoimage = "images/profile.png"
  copyright = "William Markito"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "https://twitter.com/william_markito"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "https://github.com/markito"

[[params.social]]
  medium = "medium"
  icon = "medium"
  link = "https://medium.com/@markito"

[[params.social]]
  medium = "linkedin"
  icon = "linkedin"
  link = "https://www.linkedin.com/in/markito"


[languages]
[languages.en]
languageName = "English"
weight = 1

# [languages.ptBR]
# languageName = "Português"
# weight = 2
